# Generated by Django 6.0.3 on 2026-04-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialite',
            field=models.CharField(blank=True, choices=[('scientifique', 'Scientifique'), ('economique', 'Économie & Gestion'), ('lettres', 'Lettres'), ('informatique', 'Informatique'), ('mathematiques', 'Mathématiques'), ('sciences_exp', 'Sciences Expérimentales'), ('sciences_tech', 'Sciences Techniques'), ('sciences_info', "Sciences de l'Informatique"), ('eco_gestion', 'Économie & Gestion'), ('lettres_bac', 'Lettres'), ('sport_bac', 'Sport')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='niveau',
            field=models.CharField(blank=True, choices=[('1ere', '1ère année secondaire'), ('2eme_s', '2ème année secondaire'), ('3eme_s', '3ème année secondaire'), ('4eme_s', '4ème année secondaire (Bac)')], max_length=10, null=True),
        ),
    ]
