# Generated by Django 6.0.3 on 2026-04-29 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noteseleve',
            old_name='svt',
            new_name='education_islamique',
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='gestion',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='moyenne_ponderee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='sciences_naturelles',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='technologie',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
