# Generated by Django 6.0.3 on 2026-05-09 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_svt_noteseleve_education_islamique_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noteseleve',
            old_name='moyenne_generale',
            new_name='moyenne_generale_annuelle',
        ),
        migrations.RenameField(
            model_name='noteseleve',
            old_name='moyenne_ponderee',
            new_name='moyenne_ponderee_annuelle',
        ),
        migrations.RenameField(
            model_name='noteseleve',
            old_name='niveau_global',
            new_name='niveau_global_annuel',
        ),
        migrations.RenameField(
            model_name='noteseleve',
            old_name='points_faibles',
            new_name='points_faibles_annuels',
        ),
        migrations.RenameField(
            model_name='noteseleve',
            old_name='points_forts',
            new_name='points_forts_annuels',
        ),
        migrations.RenameField(
            model_name='noteseleve',
            old_name='anglais',
            new_name='t1_anglais',
        ),
        migrations.RenameField(
            model_name='noteseleve',
            old_name='arabe',
            new_name='t1_arabe',
        ),
        migrations.RenameField(
            model_name='noteseleve',
            old_name='economie',
            new_name='t1_economie',
        ),
        migrations.RenameField(
            model_name='noteseleve',
            old_name='education_islamique',
            new_name='t1_education_islamique',
        ),
        migrations.RenameField(
            model_name='noteseleve',
            old_name='francais',
            new_name='t1_francais',
        ),
        migrations.RenameField(
            model_name='noteseleve',
            old_name='gestion',
            new_name='t1_gestion',
        ),
        migrations.RenameField(
            model_name='noteseleve',
            old_name='histoire_geo',
            new_name='t1_histoire_geo',
        ),
        migrations.RenameField(
            model_name='noteseleve',
            old_name='informatique',
            new_name='t1_informatique',
        ),
        migrations.RenameField(
            model_name='noteseleve',
            old_name='mathematiques',
            new_name='t1_mathematiques',
        ),
        migrations.RenameField(
            model_name='noteseleve',
            old_name='philosophie',
            new_name='t1_philosophie',
        ),
        migrations.RenameField(
            model_name='noteseleve',
            old_name='physique',
            new_name='t1_physique',
        ),
        migrations.RenameField(
            model_name='noteseleve',
            old_name='sciences_naturelles',
            new_name='t1_sciences_naturelles',
        ),
        migrations.RenameField(
            model_name='noteseleve',
            old_name='sport',
            new_name='t1_sport',
        ),
        migrations.RenameField(
            model_name='noteseleve',
            old_name='technologie',
            new_name='t1_technologie',
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t1_moyenne_generale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t1_moyenne_ponderee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t1_niveau_global',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t1_points_faibles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t1_points_forts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t2_anglais',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t2_arabe',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t2_economie',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t2_education_islamique',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t2_francais',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t2_gestion',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t2_histoire_geo',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t2_informatique',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t2_mathematiques',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t2_moyenne_generale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t2_moyenne_ponderee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t2_niveau_global',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t2_philosophie',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t2_physique',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t2_points_faibles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t2_points_forts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t2_sciences_naturelles',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t2_sport',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t2_technologie',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t3_anglais',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t3_arabe',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t3_economie',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t3_education_islamique',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t3_francais',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t3_gestion',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t3_histoire_geo',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t3_informatique',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t3_mathematiques',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t3_moyenne_generale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t3_moyenne_ponderee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t3_niveau_global',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t3_philosophie',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t3_physique',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t3_points_faibles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t3_points_forts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t3_sciences_naturelles',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t3_sport',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t3_technologie',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
