# Generated by Django 6.0.3 on 2026-05-09 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_rename_moyenne_generale_noteseleve_moyenne_generale_annuelle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteseleve',
            name='t1_education_civique',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t2_education_civique',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='noteseleve',
            name='t3_education_civique',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
