# Generated by Django 6.0.3 on 2026-05-10 10:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_noteseleve_t1_education_civique_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noteseleve',
            options={'verbose_name': 'Notes élève', 'verbose_name_plural': 'Notes élèves'},
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t1_anglais',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t1_arabe',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t1_economie',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t1_education_civique',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t1_education_islamique',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t1_francais',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t1_gestion',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t1_histoire_geo',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t1_informatique',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t1_mathematiques',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t1_moyenne_generale',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t1_moyenne_ponderee',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t1_niveau_global',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t1_philosophie',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t1_physique',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t1_points_faibles',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t1_points_forts',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t1_sciences_naturelles',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t1_sport',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t1_technologie',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t2_anglais',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t2_arabe',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t2_economie',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t2_education_civique',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t2_education_islamique',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t2_francais',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t2_gestion',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t2_histoire_geo',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t2_informatique',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t2_mathematiques',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t2_moyenne_generale',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t2_moyenne_ponderee',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t2_niveau_global',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t2_philosophie',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t2_physique',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t2_points_faibles',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t2_points_forts',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t2_sciences_naturelles',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t2_sport',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t2_technologie',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t3_anglais',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t3_arabe',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t3_economie',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t3_education_civique',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t3_education_islamique',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t3_francais',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t3_gestion',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t3_histoire_geo',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t3_informatique',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t3_mathematiques',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t3_moyenne_generale',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t3_moyenne_ponderee',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t3_niveau_global',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t3_philosophie',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t3_physique',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t3_points_faibles',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t3_points_forts',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t3_sciences_naturelles',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t3_sport',
        ),
        migrations.RemoveField(
            model_name='noteseleve',
            name='t3_technologie',
        ),
        migrations.AlterField(
            model_name='noteseleve',
            name='niveau_global_annuel',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent (≥ 16)'), ('Bien', 'Bien (≥ 13)'), ('Passable', 'Passable (≥ 10)'), ('Insuffisant', 'Insuffisant (< 10)')], max_length=20),
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(choices=[(1, '1er Trimestre'), (2, '2ème Trimestre'), (3, '3ème Trimestre')], help_text='1, 2 ou 3')),
                ('moyenne_generale', models.FloatField(blank=True, null=True)),
                ('moyenne_ponderee', models.FloatField(blank=True, null=True)),
                ('niveau_global', models.CharField(blank=True, choices=[('Excellent', 'Excellent (≥ 16)'), ('Bien', 'Bien (≥ 13)'), ('Passable', 'Passable (≥ 10)'), ('Insuffisant', 'Insuffisant (< 10)')], max_length=20)),
                ('points_forts', models.JSONField(blank=True, default=list)),
                ('points_faibles', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimestres', to='notes.noteseleve')),
            ],
            options={
                'verbose_name': 'Trimestre',
                'ordering': ['numero'],
                'unique_together': {('notes_eleve', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='NoteMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(help_text='Ex : mathematiques, physique, arabe…', max_length=50)),
                ('valeur', models.FloatField(help_text='Note sur 20', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('coefficient', models.PositiveSmallIntegerField(default=1, help_text="Coefficient selon la section de l'élève")),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.trimestre')),
            ],
            options={
                'verbose_name': 'Note matière',
                'ordering': ['matiere'],
                'unique_together': {('trimestre', 'matiere')},
            },
        ),
    ]
